export default {
    profile: 'Perfil',
    home:'Portada',
    about_us:'Quiénes somos',
    booking_history:'Historia de reservaciones.',
    logout:'Salir',
    notification_title:'Aviso 2Taxi.online',
    select_reason:'Selecciona el porqué cancelo.',
    no_cancel_reason:'No hay motivos de cancelación disponibles.',
    ok:'Ok',
    cancel:'Cancelar',
    select_country:'Elige un país',
    google_places_error:'Colocar ID en error de ubicación',
    not_valid_rider:'Este inicio de sesión es un usuario válido pero no Pasajero',
    new_booking_msg:'Tiene una nueva solicitud de reserva',
    no_driver:'Conductor no encontrado',
    no_bookings:'No hay reservaciones disponibles.',
    booking_cancelled:'Reservación cancelada. ID : ',
    no_cars:'No hay autos disponibles.',
    no_route:'No se ha encontrado ninguna ruta.',
    firstname:'Nombre',
    lastname:'Apellido', 
    email:'Email',
    phone:'Número del móvil',
    password:'Contraseña',
    otp:'OTP',
    profile_updated:'Perfil actualizado.',
    proper_email:'Ingrese el correo electrónico correctamente.',
    submit:'Enviar',
    booking_title:'Mis reservas',
    booking_id:'Reserva, ID',
    booking_date: 'Reserva, fecha',
    car_type: 'Tipo de auto',
    pickup_address :'Recoger en',
    drop_address: 'Destino',
    booking_status: 'Reserva, estatus',
    trip_cost:'Costo del viaje',
    payment_status:'Estatus del pago',
    cancel_booking:'Reserva, cancelar',
    select_car:'Seleccionar tipo de automóvil',
    select_booking_type:'Reserva, seleccionar tipo',
    book_now: 'Reservar ahora',
    book_later: 'Reservar posteriormente',
    book: 'Reservar',
    select_proper:'Por favor seleccione correctamente.',
    must_login:'Por favor inicie sesión para reservar',
    pickup_location:'Recoger en',
    drop_location:'Destino',
    booking_success:'Reserva exitosa. ID de reserva : ',
    myaccount: 'Mi cuenta',
    login_signup: 'Iniciar sesión / Registrarse',
    login_success:'Acceso exitoso. Necesita completar el registro.',
    login_validate_error:'El correo electrónico o la contraseña no son correctos.',
    otp_validate_error:'OTP es invalido',
    reset_pass_msg:'Enlace de restablecimiento de contraseña enviado al correo electrónico.',
    signin:'Registrarse',
    login:'Iniciar sesión',
    register:'Registrarse',
    get_otp:'Obtener OTP',
    verify_otp:'Verificar OTP',
    complete_registration:'Registro completo',
    forgot_pass_title:'Olvido la contraseña',
    forgot_pass_description:'Complete su dirección de correo electrónico y solicite. El enlace se enviará a la bandeja de entrada de su correo electrónico.',
    reset_password:'Restablecer la contraseña',
    email_tab:'Iniciar sesión por correo electrónico',
    phone_tab:'Iniciar sesión por número telefónico',
    booking_date_time:'Horario de la reservación',
    past_booking_error:'Cliente Later no está disponible para la fecha pasada o en los próximos 15 minutos.',
    booking_taken:'Se toma reserva. El conductor será asignado dentro de los 15 minutos antes de la hora de reserva. Su ID de reserva es : ',
    settings_error: 'No se pudo recuperar la configuración.',
    estimate:'Estimación de tarifa',
    auth_error:'Alerta de autenticación',
    email_verify_message:'Verifique su correo electrónico. El correo electrónico ya se envió a su bandeja de entrada.'
}