export default {
    booking_date:'Booking Date',
    trip_start_time:'Trip start Time',
    trip_end_time:'Trip End Time',
    customer_name:'Customer Name',
    car_type:'Car Type',
    vehicle_no:'Vehicle Number',
    pickup_address:'Pickup Address',
    drop_address:'Drop address',
    assign_driver:'Assign Driver',
    discount_ammount:'Discount Amount',
    payment_mode:'Payment Mode',
    booking_text:'Bookings',
    image:'Image',
    name:'Name',
    rate_per_km:'Rate Per Kilometer',
    rate_per_hour:'Rate Per Hour',
    min_fare: 'Minimum Fare',
    convenience_fee:'Convenience Fees',
    convenience_fee_percent:'Convenience Fees (%)',
    today_text:'Today',
    gross_earning:'Gross Earnings',
    admin_convenience_fee:'Our Earning',
    this_month_text:'Month',
    total:'Total',
    real_time_driver_section_text:'Drivers Realtime',
    allow_location:'Allow Location for the Realtime Map',
    sign_in:'Sign in',
    email_address:'Email Address',
    password:'password',
    sign_in_error:'Sign In Error. Please check Email and Password.',
    device_type:'Device Type',
    user_type:'User Type',
    title:'Title',
    body:'Body',
    push_notification_title:'Push Notifications',
    promo_name:'Promo Name',
    description:'Description',
    promo_type:'Promo Type',
    promo_discount_value:'Promo Value',
    max_limit:'Max Discount Allowed',
    min_limit:'Minimum Order Value',
    start_date:'Start Date',
    end_date:'End Date',
    promo_usage:'Promo Count Available',
    promo_used_by:'Promo Used By Count',
    promo_offer:'Promo and Offers',
    refferal_bonus:'Referral Bonus',
    update_failed:'Update Failed',
    first_name:'First Name',
    last_name:'Last Name',
    email:'Email',
    mobile:'Mobile',
    profile_image:'Profile Image',
    vehicle_model:'Vehicle Model',
    account_approve:'Account Approved',
    driver_active:'Driver Active Status',
    lisence_image:'License Image',
    vehicle_number:'Vehicle Number',
    wallet_balance:'Wallet Balance',
    signup_via_refferal:'Signup Via Referral',
    refferal_id:'Refferal Id',
    all_user:'All Users',
    notification_sent:' notifications sent.',
    notification_sent_failed:'Notification sending failed.',
    no_user_match:'No Users Matched',
    no_user_matching:'No users found matching your selection.',
    dashboard_text:'Dashboard',
    user:'Users',
    promo:'Promos',
    logout:'Log Out',
    driver_earning:'Driver Earning History',
    earning_amount:'Earning Amount',
    driver_name:'Driver Name',
    driver_image:'Driver Image',
    months:'Months',
    year:'Years',
    vehicle_type:'Vehicle Number',
    lisence_no:'Lisence Number',
    booking_discount_earning:'Booking Discount',
    trip_cost_driver_share:'Trip Cost/ Driver share',
    Gross_trip_cost:'Gross trip cost',
    Discounts:'Discounts',
    Customer_paid:'Customer paid',
    Profit:'Profit ( Cust paid - Trip Cost )',
    earning_reports:'Earning Reports',
    cash_payment_amount:'Cash payment amount',
    card_payment_amount:'Card payment amount',
    wallet_payment_amount:'Wallet payment amount',
    payment_getway:'Payment Getway',
    currency_symbol: 'Currency Symbol',
    currency_code: 'Currency Code',
    settings_title:'Settings',
    settings_label1:'Cash',
    settings_label2:'Wallet',
    settings_label3:'Booking OTP',
    settings_label4:'Driver Approval',
    settings_label5:'Email Verification Mandatory',
    payment_modes_title:'Payment Modes',
    queue:'Busy',
    createdAt: 'Create Date',
    security_title: 'Security Settings',
    panic_num : 'Panic Dial Number',
    addbookinglable: 'Add Bookings',
    profile: 'Profile',
    home:'Home',
    about_us:'About Us',
    booking_history:'Booking History',
    notification_title:'2Taxi Notification',
    select_reason:'Select Cancellation Reason',
    no_cancel_reason:'No cancel reasons available.',
    ok:'Ok',
    cancel:'Cancel',
    select_country:'Choose a country',
    google_places_error:'Place ID to Location Error',
    not_valid_rider:'This login is a valid user but not Rider',
    new_booking_msg:'You Have A New Booking Request',
    no_driver:'No Driver Found',
    no_bookings:'No bookings available.',
    booking_cancelled:'Booking is cancelled. ID : ',
    no_cars:'No cars available.',
    no_route:'No Route Found.',
    firstname:'First Name',
    lastname:'Last Name',
    phone:'Phone Number',
    otp:'OTP',
    profile_updated:'Profile Updated.',
    proper_email:'Please enter email properly.',
    submit:'Submit',
    booking_title:'My Bookings',
    booking_id:'Booking ID',
    booking_status: 'Booking Status',
    trip_cost:'Trip Cost',
    payment_status:'Payment Status',
    cancel_booking:'Cancel Booking',
    select_car:'Select Car Type',
    select_proper:'Please select properly.',
    must_login:'Please Login for Booking',
    pickup_location:'Pickup Location',
    drop_location:'Drop Location',
    booking_success:'Booking successful. Booking Id : ',
    myaccount: 'My Account',
    login_signup: 'Login / Sign Up',
    book_now: 'Book Now',
    login_success:'Login success. Need to complete registration.',
    login_validate_error:'Email or Password is not correct.',
    otp_validate_error:'OTP is not valid',
    reset_pass_msg:'Reset password link sent to email.',
    signin:'Sign In',
    login:'Login',
    register:'Register',
    get_otp:'Get OTP',
    verify_otp:'Verify OTP',
    complete_registration:'Complete Registration',
    forgot_pass_title:'Forgot Password',
    forgot_pass_description:'Fill up your email address and request. Link will be sent on your email inbox.',
    reset_password:'Reset Password',
    email_tab:'Email Login',
    phone_tab:'Phone Login',
    select_user:'Select User',
    other_settings:'Other Settings',
    book_later: 'Book Later',
    book: 'Book',
    booking_date_time:'Booking Data Time',
    past_booking_error:'Ride Later is not avaialable for Past Datetime or within next 15 mins.',
    booking_taken:'Booking is taken. Driver will be assigned within 15 mins before your booking time. Your Booking ID is : ',
    settings_error: 'Unable to fetch settings.',
    estimate:'Fare Estimate'
}